export const gameSettings = {
    colorSnakeGame: '#151515',
    colorMap: '#ffc66a',
    shouldShowSettings: true,
    isMapFlip: false,
    isDirectionFlip: false,
    animationImg: '',
    mapSize: '40',
    newSpeed: '4',
    randomColorSnake: false,
    shouldOpacityChange: false,
    shouldUseObstacles: false,
    shouldUseTeleports: false,
    shouldSpeedChange: false,
}